MAX_UPLOAD_SIZE_MB = 50
MAX_PORTFOLIO_IMAGES = 10
MAX_PORTFOLIO_VIDEOS = 5
MAX_PACOTE_REVISOES = 999

# Tamanhos de campo (pra evitar mágica nos models)
MAX_CHAR_NOME = 150
MAX_CHAR_EMAIL = 254
MAX_CHAR_CPF = 14
MAX_CHAR_TELEFONE = 20
MAX_CHAR_CEP = 15